namespace: learner-dev

image:
  registry: docker.io
  pullPolicy: IfNotPresent

frontend:
  image: "garapatimanoj/learnerrepcs-fe"
  tag: "dev"
  port: 80
  replicaCount: 2
  env:
    - name: REACT_APP_API_BASE
      value: /api
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "300m", memory: "256Mi" }

backend:
  image: "garapatimanoj/learnerrepcs-be"
  tag: "dev"
  port: 3000
  replicaCount: 2
  env:
    - name: NODE_ENV
      value: production
  secretEnv:
    MONGODB_URI: ""     # override via values-dev/prod or precreated Secret
  resources:
    requests: { cpu: "200m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }

ingress:
  enabled: true
  className: "nginx"
  host: "learner-dev.local"
  tls:
    enabled: false
    secretName: ""

autoscaling:
  frontend: { enabled: true, minReplicas: 2, maxReplicas: 6, targetCPUUtilizationPercentage: 70 }
  backend:  { enabled: true, minReplicas: 2, maxReplicas: 6, targetCPUUtilizationPercentage: 70 }

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
