{{- if .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: learner-report-secret
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.backend.secretEnv }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
{{- end }}
